package com.mackenzie.br.socialmedia.domain;

import java.util.Date;

import org.springframework.stereotype.Service;

import com.mackenzie.br.socialmedia.enums.InstructionLevelEnum;
import com.mackenzie.br.socialmedia.enums.ProfileTypeEnum;

@Service
public class ProfessionalDomain {
	
	private String professionalId; // might not be a Stirng, since it is auto generated by MongoDB
	
	private String name;
	
	private int age;
	
	private String userLogin;
	
	private String password;
	
	private Date birthDate;
	
	private Date careerDate;
	
	private InstructionLevelEnum instructionLevel;
	
	private ProfileTypeEnum profileType;

	public ProfessionalDomain(String name, int age, String userLogin, String password, Date birthDate, Date careerDate,
			InstructionLevelEnum instructionLevel, ProfileTypeEnum profileType) {
		this.name = name;
		this.age = age;
		this.userLogin = userLogin;
		this.password = password;
		this.birthDate = birthDate;
		this.careerDate = careerDate;
		this.instructionLevel = instructionLevel;
		this.profileType = profileType;
	}

	public String getProfessionalId() {
		return professionalId;
	}

	public void setProfessionalId(String professionalId) {
		this.professionalId = professionalId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getUserLogin() {
		return userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Date getCareerDate() {
		return careerDate;
	}

	public void setCareerDate(Date careerDate) {
		this.careerDate = careerDate;
	}

	public InstructionLevelEnum getInstructionLevel() {
		return instructionLevel;
	}

	public void setInstructionLevel(InstructionLevelEnum instructionLevel) {
		this.instructionLevel = instructionLevel;
	}

	public ProfileTypeEnum getProfileType() {
		return profileType;
	}

	public void setProfileType(ProfileTypeEnum profileType) {
		this.profileType = profileType;
	}
}
